### ISSUE TITLE
* not an issue, but a recommendation *

### ISSUE THREAD

**Issue by soypaduano** [aishek/jquery-animateNumber#29]
hello there. i was looking for something like this and I find it pretty cool. 
but,
do you think is possible to add an animation like a number counter?
more or less like this:
https://codemyui.com/click-and-drag-counter/

**Comment by aishek** [comment]
Hi, Sebastian! Thanks for kind words.

I think it is not possible to add such animation to jquery-animateNumber because it is based on generic jQuery animate. Generic jQuery animate designed for single-flow animation based on easing function. In your example there are at least two animations: number slide and dragging. Best way to implement it is write two coupled code fragments to handle each animation.

**Comment by soypaduano** [comment]
Copied. Thanks! <3
